- name: Install and setup docker
  hosts: all
  become: true 
    
  vars:
    requirements_pkgs:
    - ca-certificates
    - curl
    - gnupg
    - lvm2
    - ceph-common
    docker_pkgs:
    - docker-ce 
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

  tasks:
  - name: Install requirements
    ansible.builtin.apt:
      name: "{{ requirements_pkgs }}"
      state: present
      update_cache: true

  - name: Import Repo Key
    ansible.builtin.apt_key:
      id: "7EA0A9C3F273FCD8"
      url: "https://download.docker.com/linux/ubuntu/gpg"
      keyring: "/etc/apt/trusted.gpg.d/docker.gpg"

  - name: Install Docker repo
    ansible.builtin.copy:
      dest: "/etc/apt/sources.list.d/docker.list"
      content: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

  - name: Install Docker
    ansible.builtin.apt:
      name: "{{ docker_pkgs }}"
      state: present
      update_cache: true

  - name: Copy cephadm binary
    ansible.builtin.get_url:
      url: "https://github.com/ceph/ceph/raw/quincy/src/cephadm/cephadm"
      dest: "/usr/local/bin/cephadm"
      mode: "0755"
    when: ansible_hostname == "mon0"

  - name: Copy bootstrap config
    ansible.builtin.copy:
      src: "ceph_spec.yaml"
      dest: "/root/ceph_spec.yaml"
    when: ansible_hostname == "mon0"

  - name: Print command to deploy ceph
    ansible.builtin.debug:
      msg: "cephadm bootstrap --mon-ip={{ hostvars['mon0'].ansible_default_ipv4.address }} --apply-spec=/root/ceph_spec.yaml --initial-dashboard-user=otus --initial-dashboard-password=otus --dashboard-password-noupdate --ssh-user ubuntu --ssh-private-key /home/ubuntu/.ssh/id_rsa --ssh-public-key /home/ubuntu/.ssh/id_rsa.pub"
    run_once: true
